FROM golang:1.24-alpine AS builder

WORKDIR /src

RUN go install github.com/pressly/goose/v3/cmd/goose@v3.26.0

FROM alpine:3.20

RUN apk add --no-cache ca-certificates tzdata

COPY --from=builder /go/bin/goose /usr/local/bin/goose

WORKDIR /migrations

