// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, name, description, owner_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateProjectParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	OwnerID     uuid.UUID `json:"owner_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.Exec(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, description, owner_id, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectsForUser = `-- name: GetProjectsForUser :many
SELECT DISTINCT p.id, p.name, p.description, p.owner_id, p.created_at, p.updated_at
FROM projects p
LEFT JOIN tasks t ON t.project_id = p.id
WHERE p.owner_id = $1 OR t.assignee_id = $1
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type GetProjectsForUserParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) GetProjectsForUser(ctx context.Context, arg GetProjectsForUserParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsForUser, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskCountsByAssigneeForProject = `-- name: GetTaskCountsByAssigneeForProject :many
SELECT assignee_id, COUNT(*)::bigint AS count
FROM tasks
WHERE project_id = $1
GROUP BY assignee_id
ORDER BY count DESC
`

type GetTaskCountsByAssigneeForProjectRow struct {
	AssigneeID *uuid.UUID `json:"assignee_id"`
	Count      int64      `json:"count"`
}

func (q *Queries) GetTaskCountsByAssigneeForProject(ctx context.Context, projectID uuid.UUID) ([]GetTaskCountsByAssigneeForProjectRow, error) {
	rows, err := q.db.Query(ctx, getTaskCountsByAssigneeForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskCountsByAssigneeForProjectRow
	for rows.Next() {
		var i GetTaskCountsByAssigneeForProjectRow
		if err := rows.Scan(&i.AssigneeID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskStatusCountsForProject = `-- name: GetTaskStatusCountsForProject :many
SELECT status, COUNT(*)::bigint AS count
FROM tasks
WHERE project_id = $1
GROUP BY status
ORDER BY status
`

type GetTaskStatusCountsForProjectRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) GetTaskStatusCountsForProject(ctx context.Context, projectID uuid.UUID) ([]GetTaskStatusCountsForProjectRow, error) {
	rows, err := q.db.Query(ctx, getTaskStatusCountsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskStatusCountsForProjectRow
	for rows.Next() {
		var i GetTaskStatusCountsForProjectRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name        = COALESCE($3, name),
    description = COALESCE($4, description),
    updated_at  = $2
WHERE id = $1
RETURNING id, name, description, owner_id, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID `json:"id"`
	UpdatedAt   time.Time `json:"updated_at"`
	Name        *string   `json:"name"`
	Description *string   `json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.UpdatedAt,
		arg.Name,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
