// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (id, project_id, title, status, priority, assignee_id, due_date, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateTaskParams struct {
	ID         uuid.UUID  `json:"id"`
	ProjectID  uuid.UUID  `json:"project_id"`
	Title      string     `json:"title"`
	Status     string     `json:"status"`
	Priority   string     `json:"priority"`
	AssigneeID *uuid.UUID `json:"assignee_id"`
	DueDate    *time.Time `json:"due_date"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.Exec(ctx, createTask,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.DueDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, project_id, title, status, priority, assignee_id, due_date, created_at, updated_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTasksByProject = `-- name: GetTasksByProject :many
SELECT id, project_id, title, status, priority, assignee_id, due_date, created_at, updated_at
FROM tasks
WHERE project_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::uuid IS NULL OR assignee_id = $3)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type GetTasksByProjectParams struct {
	ProjectID  uuid.UUID  `json:"project_id"`
	Status     *string    `json:"status"`
	AssigneeID *uuid.UUID `json:"assignee_id"`
	Offset     int32      `json:"offset"`
	Limit      int32      `json:"limit"`
}

func (q *Queries) GetTasksByProject(ctx context.Context, arg GetTasksByProjectParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksByProject,
		arg.ProjectID,
		arg.Status,
		arg.AssigneeID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title       = COALESCE($3, title),
    status      = COALESCE($4, status),
    priority    = COALESCE($5, priority),
    assignee_id = COALESCE($6, assignee_id),
    due_date    = COALESCE($7, due_date),
    updated_at  = $2
WHERE id = $1
RETURNING id, project_id, title, status, priority, assignee_id, due_date, created_at, updated_at
`

type UpdateTaskParams struct {
	ID         uuid.UUID  `json:"id"`
	UpdatedAt  time.Time  `json:"updated_at"`
	Title      *string    `json:"title"`
	Status     *string    `json:"status"`
	Priority   *string    `json:"priority"`
	AssigneeID *uuid.UUID `json:"assignee_id"`
	DueDate    *time.Time `json:"due_date"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.UpdatedAt,
		arg.Title,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
