// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	RefreshTokenHash    string             `json:"refresh_token_hash"`
	UserAgent           *string            `json:"user_agent"`
	IpAddress           *netip.Addr        `json:"ip_address"`
	DeviceName          *string            `json:"device_name"`
	CreatedAt           time.Time          `json:"created_at"`
	LastUsedAt          pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt           time.Time          `json:"expires_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBySessionID *uuid.UUID         `json:"replaced_by_session_id"`
}

type Project struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	OwnerID     uuid.UUID `json:"owner_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Task struct {
	ID         uuid.UUID  `json:"id"`
	ProjectID  uuid.UUID  `json:"project_id"`
	Title      string     `json:"title"`
	Status     string     `json:"status"`
	Priority   string     `json:"priority"`
	AssigneeID *uuid.UUID `json:"assignee_id"`
	DueDate    *time.Time `json:"due_date"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
