// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :exec
INSERT INTO auth_sessions (
    id, user_id, refresh_token_hash, user_agent, ip_address, device_name,
    created_at, last_used_at, expires_at, revoked_at, replaced_by_session_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateAuthSessionParams struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	RefreshTokenHash    string             `json:"refresh_token_hash"`
	UserAgent           *string            `json:"user_agent"`
	IpAddress           *netip.Addr        `json:"ip_address"`
	DeviceName          *string            `json:"device_name"`
	CreatedAt           time.Time          `json:"created_at"`
	LastUsedAt          pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt           time.Time          `json:"expires_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBySessionID *uuid.UUID         `json:"replaced_by_session_id"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error {
	_, err := q.db.Exec(ctx, createAuthSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.DeviceName,
		arg.CreatedAt,
		arg.LastUsedAt,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.ReplacedBySessionID,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, name, email, password_hash, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}

const getAuthSessionByID = `-- name: GetAuthSessionByID :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, device_name,
       created_at, last_used_at, expires_at, revoked_at, replaced_by_session_id
FROM auth_sessions
WHERE id = $1
`

func (q *Queries) GetAuthSessionByID(ctx context.Context, id uuid.UUID) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByID, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.DeviceName,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBySessionID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, created_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllAuthSessionsForUser = `-- name: RevokeAllAuthSessionsForUser :exec
UPDATE auth_sessions
SET revoked_at = $2
WHERE user_id = $1
  AND revoked_at IS NULL
`

type RevokeAllAuthSessionsForUserParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeAllAuthSessionsForUser(ctx context.Context, arg RevokeAllAuthSessionsForUserParams) error {
	_, err := q.db.Exec(ctx, revokeAllAuthSessionsForUser, arg.UserID, arg.RevokedAt)
	return err
}

const revokeAuthSession = `-- name: RevokeAuthSession :exec
UPDATE auth_sessions
SET revoked_at = $2,
    replaced_by_session_id = $3
WHERE id = $1
`

type RevokeAuthSessionParams struct {
	ID                  uuid.UUID          `json:"id"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBySessionID *uuid.UUID         `json:"replaced_by_session_id"`
}

func (q *Queries) RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) error {
	_, err := q.db.Exec(ctx, revokeAuthSession, arg.ID, arg.RevokedAt, arg.ReplacedBySessionID)
	return err
}

const updateAuthSessionLastUsedAt = `-- name: UpdateAuthSessionLastUsedAt :exec
UPDATE auth_sessions
SET last_used_at = $2
WHERE id = $1
`

type UpdateAuthSessionLastUsedAtParams struct {
	ID         uuid.UUID          `json:"id"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) UpdateAuthSessionLastUsedAt(ctx context.Context, arg UpdateAuthSessionLastUsedAtParams) error {
	_, err := q.db.Exec(ctx, updateAuthSessionLastUsedAt, arg.ID, arg.LastUsedAt)
	return err
}
